version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10

  - package-ecosystem: 'npm'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      dependencies-major:
        dependency-type: 'production'
        update-types:
          - 'major'
      dev-dependencies:
        dependency-type: 'development'
