version: "3.8"
services:

  redis:
    image: redis:latest
    container_name: ${REDIS_SERVER}
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    volumes:
      - ./.docker/redis/storage:/data
    restart: always

  mysql:
    image: mysql:latest
    container_name: ${MYSQL_SERVER}
    restart: always
    command: "--character-set-server=utf8mb4"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.docker/mysql/scripts:/docker-entrypoint-initdb.d/
      - ./.docker/mysql/storage:/var/lib/mysql:rw
      - ./.docker/mysql/logs:/var/lib/mysql-logs:rw

networks:
  default:
    driver: bridge